postgresql:
        address: "127.0.0.1:5432"
        username: "weasel"
        password: ""
        database: "postgres"

path:
        templates: "/srv/src/weasel/templates/pages"
        static: "/srv/src/weasel/static/"
